const colors = {
  light: {
    text: "#0C0A09",
    tint: "#2E7D32",
    background: "#FAFAFA",
    foreground: "#0C0A09",
    card: "#FFFFFF",
    cardForeground: "#0C0A09",
    primary: "#2E7D32",
    primaryForeground: "#FAFAFA",
    secondary: "#F4F4F0",
    secondaryForeground: "#1A1A1A",
    muted: "#F4F4F0",
    mutedForeground: "#78716C",
    accent: "#F4F4F0",
    accentForeground: "#1A1A1A",
    destructive: "#EF4444",
    destructiveForeground: "#FAFAFA",
    border: "#E7E5E4",
    input: "#E7E5E4",
    islamicGreen: "#2E7D32",
    islamicLight: "#4CAF50",
    islamicAccent: "#FF9800",
    islamicDark: "#1B5E20",
    success: "#4CAF50",
    successForeground: "#FFFFFF",
  },
  dark: {
    text: "#FAFAFA",
    tint: "#4CAF50",
    background: "#09090B",
    foreground: "#FAFAFA",
    card: "#09090B",
    cardForeground: "#FAFAFA",
    primary: "#4CAF50",
    primaryForeground: "#09090B",
    secondary: "#27272A",
    secondaryForeground: "#FAFAFA",
    muted: "#27272A",
    mutedForeground: "#A1A1AA",
    accent: "#27272A",
    accentForeground: "#FAFAFA",
    destructive: "#7F1D1D",
    destructiveForeground: "#FAFAFA",
    border: "#27272A",
    input: "#27272A",
    islamicGreen: "#4CAF50",
    islamicLight: "#66BB6A",
    islamicAccent: "#FFB74D",
    islamicDark: "#2E7D32",
    success: "#4CAF50",
    successForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
